# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='log_info',
        ),
        migrations.AddField(
            model_name='userlog',
            name='favourite',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='userlog',
            name='like',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='userlog',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
