# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itube', '0003_remove_userlog_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='favourite',
            field=models.BooleanField(default=None),
        ),
    ]
