# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itube', '0004_userlog_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='favourite',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='like',
            field=models.NullBooleanField(default=None),
        ),
    ]
