# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itube', '0007_userlog_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='favourite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
