# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itube', '0008_auto_20170420_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='query',
            field=models.CharField(max_length=100),
        ),
    ]
